[project]
name = "ingrain-model-server"
version = "0.2.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "certifi>=2025.11.12",
    "fastapi==0.124.2",
    "hf-transfer==0.1.9",
    "onnx==1.20.0",
    "onnxconverter-common>=1.16.0",
    "onnxoptimizer>=0.3.13",
    "onnxscript>=0.5.6",
    "open-clip-torch==3.2.0",
    "orjson==3.11.5",
    "pillow==12.0.0",
    "pycurl==7.45.7",
    "pydantic==2.12.5",
    "sentence-transformers==5.2.0",
    "timm==1.0.22",
    "tokenizers==0.22.1",
    "torch==2.9.1+cpu ; platform_machine == 'x86_64'",
    "torch==2.9.1 ; platform_machine == 'aarch64'",
    "torchvision==0.24.1+cpu ; platform_machine == 'x86_64'",
    "torchvision==0.24.1 ; platform_machine == 'aarch64'",
    "transformers==4.56.0",
    "tritonclient[grpc]>=2.63.0",
    "uvicorn==0.35.0",
    "validators==0.35.0",
    "huggingface_hub[hf_xet]>=0.36.0",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]
torchvision = [
  { index = "pytorch-cpu" },
]